// Crop catalogue for Farmdirect.
// A single crop row in the DB describes one produce item the marketplace
// recognises. Seed data is derived from CROP_CATALOG below, and listings are
// created against these rows so that availability ("crops available on this
// farm") and per-crop metadata stay consistent everywhere.

export type CropSeed = {
  name: string;
  slug: string;
  category:
    | "Vegetables"
    | "Fruits"
    | "Grains"
    | "Pulses"
    | "Oilseeds"
    | "Other";
  subcategory: string;
  emoji: string;
  tint: number; // index into the client crop-art palette (0-15)
  unit: string; // trading unit, e.g. "kg" | "quintal" | "dozen"
  marketPrice: number; // demo market price in ₹ per unit
  shelfLifeDays: number;
  organicDefault: boolean;
  description: string;
};

export const CROP_CATALOG: CropSeed[] = [
  // ─────────────────────────── VEGETABLES ───────────────────────────
  {
    name: "Tomato",
    slug: "tomato",
    category: "Vegetables",
    subcategory: "Fruiting Vegetables",
    emoji: "🍅",
    tint: 6,
    unit: "kg",
    marketPrice: 30,
    shelfLifeDays: 7,
    organicDefault: false,
    description:
      "Deep red, farm-ripened table tomatoes. Firm flesh, tangy-sweet — ideal for daily kitchens and processing.",
  },
  {
    name: "Potato",
    slug: "potato",
    category: "Vegetables",
    subcategory: "Root & Bulb Vegetables",
    emoji: "🥔",
    tint: 1,
    unit: "kg",
    marketPrice: 26,
    shelfLifeDays: 21,
    organicDefault: false,
    description:
      "High-yield round potatoes with smooth skin. Uniform size, low moisture — good for storage and bulk buyers.",
  },
  {
    name: "Onion",
    slug: "onion",
    category: "Vegetables",
    subcategory: "Root & Bulb Vegetables",
    emoji: "🧅",
    tint: 3,
    unit: "kg",
    marketPrice: 32,
    shelfLifeDays: 30,
    organicDefault: false,
    description:
      "Pungent kharif onions, cured and sorted. Pungency and keeping quality make them a market staple.",
  },
  {
    name: "Carrot",
    slug: "carrot",
    category: "Vegetables",
    subcategory: "Root & Bulb Vegetables",
    emoji: "🥕",
    tint: 5,
    unit: "kg",
    marketPrice: 38,
    shelfLifeDays: 14,
    organicDefault: false,
    description:
      "Bright orange, tender carrots harvested in the morning. Sweet crunch, heavy for their size.",
  },
  {
    name: "Cauliflower",
    slug: "cauliflower",
    category: "Vegetables",
    subcategory: "Cruciferous",
    emoji: "🥦",
    tint: 0,
    unit: "kg",
    marketPrice: 42,
    shelfLifeDays: 10,
    organicDefault: false,
    description:
      "Snow-white compact curds with fresh green wrapper leaves. Trimmed and packed the same morning.",
  },
  {
    name: "Cabbage",
    slug: "cabbage",
    category: "Vegetables",
    subcategory: "Cruciferous",
    emoji: "🥬",
    tint: 2,
    unit: "kg",
    marketPrice: 24,
    shelfLifeDays: 12,
    organicDefault: false,
    description:
      "Tight, heavy heads of crisp green cabbage. Uniform size, ideal for wholesale and retail lots.",
  },
  {
    name: "Okra (Ladyfinger)",
    slug: "okra",
    category: "Vegetables",
    subcategory: "Fruiting Vegetables",
    emoji: "🫛",
    tint: 4,
    unit: "kg",
    marketPrice: 48,
    shelfLifeDays: 4,
    organicDefault: false,
    description:
      "Tender, non-fibrous bhindi picked young at dawn. Bright green pods, packed without water spray.",
  },
  {
    name: "Brinjal (Eggplant)",
    slug: "brinjal",
    category: "Vegetables",
    subcategory: "Fruiting Vegetables",
    emoji: "🍆",
    tint: 8,
    unit: "kg",
    marketPrice: 34,
    shelfLifeDays: 6,
    organicDefault: false,
    description:
      "Shiny purple long brinjals with few seeds. Glossy skin, firm pulp — excellent for curries and stuffing.",
  },
  {
    name: "Green Chilli",
    slug: "green-chilli",
    category: "Vegetables",
    subcategory: "Fruiting Vegetables",
    emoji: "🌶️",
    tint: 9,
    unit: "kg",
    marketPrice: 62,
    shelfLifeDays: 7,
    organicDefault: false,
    description:
      "Hot, thin-skinned green chillies with a sharp aroma. Picked green and crated within hours.",
  },
  {
    name: "Capsicum (Bell Pepper)",
    slug: "capsicum",
    category: "Vegetables",
    subcategory: "Fruiting Vegetables",
    emoji: "🫑",
    tint: 4,
    unit: "kg",
    marketPrice: 68,
    shelfLifeDays: 8,
    organicDefault: false,
    description:
      "Thick-walled, sweet green capsicum. High gloss, crunchy bite — greenhouse and open-field lots.",
  },
  {
    name: "Green Peas",
    slug: "green-peas",
    category: "Vegetables",
    subcategory: "Legumes & Beans",
    emoji: "🟢",
    tint: 10,
    unit: "kg",
    marketPrice: 74,
    shelfLifeDays: 5,
    organicDefault: false,
    description:
      "Sweet early-harvest peas shelled daily. Small, tender grains with high sugar content.",
  },
  {
    name: "Spinach (Palak)",
    slug: "spinach",
    category: "Vegetables",
    subcategory: "Leafy Greens & Herbs",
    emoji: "🍃",
    tint: 10,
    unit: "bunch",
    marketPrice: 15,
    shelfLifeDays: 3,
    organicDefault: true,
    description:
      "Dark green, tender palak bunched each morning. Chemical-spray-free leafy greens for the freshest saag.",
  },
  {
    name: "Coriander (Dhania)",
    slug: "coriander",
    category: "Vegetables",
    subcategory: "Leafy Greens & Herbs",
    emoji: "🌿",
    tint: 2,
    unit: "bunch",
    marketPrice: 12,
    shelfLifeDays: 3,
    organicDefault: true,
    description:
      "Fragrant, freshly cut coriander bunches with strong stems. Grown on raised beds, cut at dawn.",
  },
  {
    name: "Radish",
    slug: "radish",
    category: "Vegetables",
    subcategory: "Root & Bulb Vegetables",
    emoji: "🍥",
    tint: 9,
    unit: "kg",
    marketPrice: 24,
    shelfLifeDays: 10,
    organicDefault: false,
    description:
      "Crisp, mildly pungent white radish with edible greens. Pulled fresh, cleaned and topped.",
  },
  {
    name: "Beetroot",
    slug: "beetroot",
    category: "Vegetables",
    subcategory: "Root & Bulb Vegetables",
    emoji: "🍠",
    tint: 11,
    unit: "kg",
    marketPrice: 42,
    shelfLifeDays: 14,
    organicDefault: false,
    description:
      "Deep maroon, sweet beetroots with intact rootlets. Uniform 150–200 g roots, dirt-free.",
  },
  {
    name: "Bottle Gourd (Lauki)",
    slug: "bottle-gourd",
    category: "Vegetables",
    subcategory: "Gourds",
    emoji: "🍈",
    tint: 7,
    unit: "kg",
    marketPrice: 30,
    shelfLifeDays: 9,
    organicDefault: false,
    description:
      "Tender, light-green lauki with soft edible skin. High water content, easy to peel and cook.",
  },
  {
    name: "Bitter Gourd (Karela)",
    slug: "bitter-gourd",
    category: "Vegetables",
    subcategory: "Gourds",
    emoji: "🥒",
    tint: 0,
    unit: "kg",
    marketPrice: 52,
    shelfLifeDays: 6,
    organicDefault: false,
    description:
      "Knobby, deep-green karela of medium bitterness. Harvested at the right size for best texture.",
  },
  {
    name: "Ridge Gourd (Turai)",
    slug: "ridge-gourd",
    category: "Vegetables",
    subcategory: "Gourds",
    emoji: "🥒",
    tint: 3,
    unit: "kg",
    marketPrice: 40,
    shelfLifeDays: 5,
    organicDefault: false,
    description:
      "Fresh ridged turai cut young, before seeds harden. Soft and quick-cooking.",
  },
  {
    name: "Pumpkin",
    slug: "pumpkin",
    category: "Vegetables",
    subcategory: "Gourds",
    emoji: "🎃",
    tint: 12,
    unit: "kg",
    marketPrice: 26,
    shelfLifeDays: 40,
    organicDefault: false,
    description:
      "Mature orange pumpkin with thick, sweet flesh. Long shelf life — reliable for steady supply.",
  },
  {
    name: "Cucumber",
    slug: "cucumber",
    category: "Vegetables",
    subcategory: "Fruiting Vegetables",
    emoji: "🥒",
    tint: 2,
    unit: "kg",
    marketPrice: 32,
    shelfLifeDays: 6,
    organicDefault: false,
    description:
      "Straight, dark-green cucumbers with tender spines. Crisp texture and mild flavour.",
  },
  {
    name: "Broccoli",
    slug: "broccoli",
    category: "Vegetables",
    subcategory: "Cruciferous",
    emoji: "🥦",
    tint: 4,
    unit: "kg",
    marketPrice: 128,
    shelfLifeDays: 5,
    organicDefault: true,
    description:
      "Tight, dark-green broccoli heads with firm stalks. Grown on compost beds, cold-chained to dispatch.",
  },
  {
    name: "French Beans",
    slug: "french-beans",
    category: "Vegetables",
    subcategory: "Legumes & Beans",
    emoji: "🫛",
    tint: 5,
    unit: "kg",
    marketPrice: 84,
    shelfLifeDays: 5,
    organicDefault: false,
    description:
      "Slender, stringless French beans picked at pencil thickness. Snap-fresh all the way.",
  },
  {
    name: "Sweet Corn",
    slug: "sweet-corn",
    category: "Vegetables",
    subcategory: "Fruiting Vegetables",
    emoji: "🌽",
    tint: 13,
    unit: "kg",
    marketPrice: 30,
    shelfLifeDays: 4,
    organicDefault: false,
    description:
      "High-sugar corn cobs with milky kernels. Harvested at peak sweetness, husks intact.",
  },
  {
    name: "Green Beans",
    slug: "green-beans",
    category: "Vegetables",
    subcategory: "Legumes & Beans",
    emoji: "🫘",
    tint: 7,
    unit: "kg",
    marketPrice: 70,
    shelfLifeDays: 6,
    organicDefault: false,
    description:
      "Plump, young cluster beans with mild flavour. Hand-picked and graded the same day.",
  },
  {
    name: "Garlic",
    slug: "garlic",
    category: "Vegetables",
    subcategory: "Root & Bulb Vegetables",
    emoji: "🧄",
    tint: 14,
    unit: "kg",
    marketPrice: 95,
    shelfLifeDays: 45,
    organicDefault: false,
    description:
      "Pungent, well-cured garlic bulbs with tight cloves. High allicin content — premium culinary grade.",
  },
  {
    name: "Ginger",
    slug: "ginger",
    category: "Vegetables",
    subcategory: "Root & Bulb Vegetables",
    emoji: "🫚",
    tint: 1,
    unit: "kg",
    marketPrice: 88,
    shelfLifeDays: 20,
    organicDefault: false,
    description:
      "Fleshy, mild-hot ginger rhizomes freshly dug. Juicy and aromatic, ideal for culinary use.",
  },

  // ────────────────────────────── FRUITS ─────────────────────────────
  {
    name: "Mango",
    slug: "mango",
    category: "Fruits",
    subcategory: "Tropical Fruits",
    emoji: "🥭",
    tint: 6,
    unit: "kg",
    marketPrice: 90,
    shelfLifeDays: 6,
    organicDefault: false,
    description:
      "Orchard-ripened Alphonso/Banganapalli mangoes with rich aroma. Graded, fibre-free and carefully packed.",
  },
  {
    name: "Banana",
    slug: "banana",
    category: "Fruits",
    subcategory: "Tropical Fruits",
    emoji: "🍌",
    tint: 13,
    unit: "dozen",
    marketPrice: 45,
    shelfLifeDays: 5,
    organicDefault: false,
    description:
      "Curvature-grade Robusta bananas in green-yellow stage for safe transport. Uniform fingers.",
  },
  {
    name: "Apple",
    slug: "apple",
    category: "Fruits",
    subcategory: "Temperate Fruits",
    emoji: "🍎",
    tint: 8,
    unit: "kg",
    marketPrice: 160,
    shelfLifeDays: 25,
    organicDefault: false,
    description:
      "Crisp, high-colour apples from high-altitude orchards. Firm flesh, cold-stored to keep crunch.",
  },
  {
    name: "Orange",
    slug: "orange",
    category: "Fruits",
    subcategory: "Citrus Fruits",
    emoji: "🍊",
    tint: 12,
    unit: "kg",
    marketPrice: 70,
    shelfLifeDays: 12,
    organicDefault: false,
    description:
      "Juicy Nagpur-style oranges with tight skin and high juice content. Sweet with a balanced tang.",
  },
  {
    name: "Guava",
    slug: "guava",
    category: "Fruits",
    subcategory: "Tropical Fruits",
    emoji: "🍐",
    tint: 9,
    unit: "kg",
    marketPrice: 50,
    shelfLifeDays: 7,
    organicDefault: false,
    description:
      "Large, cream-fleshed guavas with thin green-gold skin. Aromatic and low in seeds.",
  },
  {
    name: "Papaya",
    slug: "papaya",
    category: "Fruits",
    subcategory: "Tropical Fruits",
    emoji: "🍈",
    tint: 4,
    unit: "kg",
    marketPrice: 45,
    shelfLifeDays: 8,
    organicDefault: false,
    description:
      "Red-flesh papayas harvested at 1/4 ripeness for safe dispatch. Smooth, sweet and fibre-rich.",
  },
  {
    name: "Pomegranate",
    slug: "pomegranate",
    category: "Fruits",
    subcategory: "Tropical Fruits",
    emoji: "🍎",
    tint: 11,
    unit: "kg",
    marketPrice: 130,
    shelfLifeDays: 20,
    organicDefault: false,
    description:
      "Ruby-red, soft-seed pomegranates with deep-coloured arils. High juice, thick skin for transport.",
  },
  {
    name: "Watermelon",
    slug: "watermelon",
    category: "Fruits",
    subcategory: "Melons",
    emoji: "🍉",
    tint: 2,
    unit: "kg",
    marketPrice: 22,
    shelfLifeDays: 10,
    organicDefault: false,
    description:
      "Sugar-content checked watermelons, heavy for their size. Crimson, crisp flesh.",
  },
  {
    name: "Muskmelon",
    slug: "muskmelon",
    category: "Fruits",
    subcategory: "Melons",
    emoji: "🍈",
    tint: 6,
    unit: "kg",
    marketPrice: 35,
    shelfLifeDays: 6,
    organicDefault: false,
    description:
      "Net-skinned muskmelons with aromatic, honey-sweet flesh. Picked at slip stage for ripeness.",
  },
  {
    name: "Grapes",
    slug: "grapes",
    category: "Fruits",
    subcategory: "Temperate Fruits",
    emoji: "🍇",
    tint: 8,
    unit: "kg",
    marketPrice: 95,
    shelfLifeDays: 9,
    organicDefault: false,
    description:
      "Seedless Thompson/Sonaka grapes with bloom intact. Cool-chain packed in ventilated punnets.",
  },
  {
    name: "Lemon",
    slug: "lemon",
    category: "Fruits",
    subcategory: "Citrus Fruits",
    emoji: "🍋",
    tint: 13,
    unit: "kg",
    marketPrice: 55,
    shelfLifeDays: 15,
    organicDefault: false,
    description:
      "Thin-skinned, high-juice lemons with strong aroma. Deep yellow, sorted by size.",
  },

  // ────────────────────────────── GRAINS ─────────────────────────────
  {
    name: "Wheat",
    slug: "wheat",
    category: "Grains",
    subcategory: "Cereals",
    emoji: "🌾",
    tint: 1,
    unit: "quintal",
    marketPrice: 2450,
    shelfLifeDays: 365,
    organicDefault: false,
    description:
      "HD-3086 grade wheat, sun-dried to 12% moisture, machine-cleaned and bagged for milling.",
  },
  {
    name: "Rice (Paddy Parboiled)",
    slug: "rice",
    category: "Grains",
    subcategory: "Cereals",
    emoji: "🍚",
    tint: 14,
    unit: "quintal",
    marketPrice: 3800,
    shelfLifeDays: 365,
    organicDefault: false,
    description:
      "Parboiled paddy of uniform grain length, dried and graded. High milling recovery.",
  },
  {
    name: "Paddy (Raw)",
    slug: "paddy",
    category: "Grains",
    subcategory: "Cereals",
    emoji: "🌾",
    tint: 5,
    unit: "quintal",
    marketPrice: 2350,
    shelfLifeDays: 300,
    organicDefault: false,
    description:
      "Fresh-season raw paddy at 14% moisture. Clean, well-filled grains suitable for milling contracts.",
  },
  {
    name: "Maize",
    slug: "maize",
    category: "Grains",
    subcategory: "Cereals",
    emoji: "🌽",
    tint: 10,
    unit: "quintal",
    marketPrice: 2250,
    shelfLifeDays: 300,
    organicDefault: false,
    description:
      "Flint maize with bold yellow kernels, dried and de-husked. For feed and starch industries.",
  },
  {
    name: "Barley",
    slug: "barley",
    category: "Grains",
    subcategory: "Cereals",
    emoji: "🌾",
    tint: 3,
    unit: "quintal",
    marketPrice: 2150,
    shelfLifeDays: 300,
    organicDefault: false,
    description:
      "Two-row barley with plump grains for malting and flour. Clean, low foreign matter.",
  },
  {
    name: "Bajra (Pearl Millet)",
    slug: "bajra",
    category: "Grains",
    subcategory: "Millets",
    emoji: "🌾",
    tint: 2,
    unit: "quintal",
    marketPrice: 2350,
    shelfLifeDays: 300,
    organicDefault: true,
    description:
      "Drought-grown pearl millet, chemical-spray-free. Bold grey grains with high protein.",
  },
  {
    name: "Jowar (Sorghum)",
    slug: "jowar",
    category: "Grains",
    subcategory: "Millets",
    emoji: "🌾",
    tint: 4,
    unit: "quintal",
    marketPrice: 2600,
    shelfLifeDays: 300,
    organicDefault: false,
    description:
      "White jowar with bold grains. Sun-dried and cleaned for roti flour and processing.",
  },
  {
    name: "Ragi (Finger Millet)",
    slug: "ragi",
    category: "Grains",
    subcategory: "Millets",
    emoji: "🟤",
    tint: 9,
    unit: "quintal",
    marketPrice: 3200,
    shelfLifeDays: 300,
    organicDefault: true,
    description:
      "Brown ragi grown on natural rain-fed land. Stone-cleaned, high calcium, for flour and malt.",
  },

  // ────────────────────────────── PULSES ─────────────────────────────
  {
    name: "Lentils (Masoor)",
    slug: "lentils",
    category: "Pulses",
    subcategory: "Pulses",
    emoji: "🟠",
    tint: 7,
    unit: "kg",
    marketPrice: 120,
    shelfLifeDays: 365,
    organicDefault: false,
    description:
      "Salmon-pink masoor dal of even size. Machine-cleaned, low moisture, quick-cooking.",
  },
  {
    name: "Chickpea (Chana)",
    slug: "chickpea",
    category: "Pulses",
    subcategory: "Pulses",
    emoji: "🟤",
    tint: 10,
    unit: "kg",
    marketPrice: 115,
    shelfLifeDays: 365,
    organicDefault: false,
    description:
      "Bold desi chickpeas with good test weight. Cleaned and graded for dal mills and retail.",
  },
  {
    name: "Green Gram (Moong)",
    slug: "green-gram",
    category: "Pulses",
    subcategory: "Pulses",
    emoji: "🟢",
    tint: 8,
    unit: "kg",
    marketPrice: 110,
    shelfLifeDays: 365,
    organicDefault: false,
    description:
      "Uniform green moong with shiny coat. Machine-cleaned, ideal for sprouting and dal.",
  },
  {
    name: "Black Gram (Urad)",
    slug: "black-gram",
    category: "Pulses",
    subcategory: "Pulses",
    emoji: "⬛",
    tint: 6,
    unit: "kg",
    marketPrice: 105,
    shelfLifeDays: 365,
    organicDefault: false,
    description:
      "Shiny black urad with high protein. Cleaned of stones and immature grains.",
  },
  {
    name: "Pigeon Pea (Arhar/Toor)",
    slug: "pigeon-pea",
    category: "Pulses",
    subcategory: "Pulses",
    emoji: "🟡",
    tint: 5,
    unit: "kg",
    marketPrice: 115,
    shelfLifeDays: 365,
    organicDefault: false,
    description:
      "Bold toor with natural shine. Fresh-season stock, ideal for dal mills.",
  },

  // ────────────────────────────── OILSEEDS ─────────────────────────────
  {
    name: "Mustard (Rai)",
    slug: "mustard",
    category: "Oilseeds",
    subcategory: "Oilseeds",
    emoji: "🟡",
    tint: 13,
    unit: "kg",
    marketPrice: 65,
    shelfLifeDays: 300,
    organicDefault: false,
    description:
      "Pungent black mustard seed for oil and sarson saag. Clean, bold and uniform.",
  },
  {
    name: "Groundnut (Peanut)",
    slug: "groundnut",
    category: "Oilseeds",
    subcategory: "Oilseeds",
    emoji: "🥜",
    tint: 1,
    unit: "kg",
    marketPrice: 75,
    shelfLifeDays: 200,
    organicDefault: false,
    description:
      "Kernelled bold groundnut with high oil recovery. Fresh crop, low aflatoxin risk.",
  },
  {
    name: "Soybean",
    slug: "soybean",
    category: "Oilseeds",
    subcategory: "Oilseeds",
    emoji: "🟡",
    tint: 10,
    unit: "kg",
    marketPrice: 52,
    shelfLifeDays: 300,
    organicDefault: false,
    description:
      "Non-GMO soybean with high protein content. Cleaned and graded for crushing and feed.",
  },
  {
    name: "Sesame (Til)",
    slug: "sesame",
    category: "Oilseeds",
    subcategory: "Oilseeds",
    emoji: "🤍",
    tint: 14,
    unit: "kg",
    marketPrice: 140,
    shelfLifeDays: 300,
    organicDefault: true,
    description:
      "Natural white sesame with high oil content. Export-grade clean, used in confectionery.",
  },
  {
    name: "Sunflower",
    slug: "sunflower",
    category: "Oilseeds",
    subcategory: "Oilseeds",
    emoji: "🌻",
    tint: 12,
    unit: "kg",
    marketPrice: 90,
    shelfLifeDays: 200,
    organicDefault: false,
    description:
      "Striped sunflower seed with good oil yield. Cleaned and dried for expeller crushing.",
  },

  // ─────────────────────────────── OTHER ──────────────────────────────
  {
    name: "Turmeric",
    slug: "turmeric",
    category: "Other",
    subcategory: "Spices & Commercial Crops",
    emoji: "🟠",
    tint: 5,
    unit: "kg",
    marketPrice: 160,
    shelfLifeDays: 365,
    organicDefault: false,
    description:
      "High-curcumin Salem/Erode turmeric fingers, cured and polished. For spice mills and retail.",
  },
  {
    name: "Coriander Seeds",
    slug: "coriander-seeds",
    category: "Other",
    subcategory: "Spices & Commercial Crops",
    emoji: "🟫",
    tint: 3,
    unit: "kg",
    marketPrice: 95,
    shelfLifeDays: 365,
    organicDefault: false,
    description:
      "Aromatic coriander seeds with high volatile oil. Sun-dried and cleaned for spice grinding.",
  },
  {
    name: "Red Chilli (Dry)",
    slug: "red-chilli-dry",
    category: "Other",
    subcategory: "Spices & Commercial Crops",
    emoji: "🌶️",
    tint: 9,
    unit: "kg",
    marketPrice: 190,
    shelfLifeDays: 365,
    organicDefault: false,
    description:
      "Deep-red Byadgi dry chillies with high colour value. Sun-dried on mats, sorted by size.",
  },
  {
    name: "Sugarcane",
    slug: "sugarcane",
    category: "Other",
    subcategory: "Commercial Crops",
    emoji: "🎋",
    tint: 10,
    unit: "quintal",
    marketPrice: 350,
    shelfLifeDays: 14,
    organicDefault: false,
    description:
      "High-brix cane for jaggery and mills. Fresh-cut with green tops, contracted lots available.",
  },
  {
    name: "Cotton (Kapas)",
    slug: "cotton",
    category: "Other",
    subcategory: "Commercial Crops",
    emoji: "☁️",
    tint: 14,
    unit: "quintal",
    marketPrice: 7500,
    shelfLifeDays: 365,
    organicDefault: false,
    description:
      "Clean kapas with high ginning percentage. Low trash content, pressed bales on request.",
  },
];

export const CATEGORY_LABELS = [
  { key: "Vegetables", emoji: "🥦" },
  { key: "Fruits", emoji: "🥭" },
  { key: "Grains", emoji: "🌾" },
  { key: "Pulses", emoji: "🫘" },
  { key: "Oilseeds", emoji: "🌻" },
  { key: "Other", emoji: "🌶️" },
] as const;
